import { useMemo, useState } from "react";
import { Download, GitPullRequestArrow, Play, RotateCcw } from "lucide-react";
import { Project, ProjectTable, SchemaColumn, TableReference } from "../lib/api";

function columnNote(column: SchemaColumn) {
  const notes = [];
  if (column.primaryKey) notes.push("Primary key");
  if (column.unique) notes.push("Unique");
  if (column.default) notes.push(`Default: ${column.default}`);
  if (column.foreignKey) notes.push(`References ${column.foreignKey.table}.${column.foreignKey.column}`);
  return notes.join(" · ") || "Generated by Gemini";
}

function referenceLabel(reference: TableReference, tables: ProjectTable[]) {
  const fromTable = tables.find((table) => table.id === reference.fromTableId)?.name ?? "unknown";
  const toTable = tables.find((table) => table.id === reference.toTableId)?.name ?? "unknown";
  return `${fromTable}.${reference.fromCol} -> ${toTable}.${reference.toCol}`;
}

export function SchemaWorkspace({
  project,
  isLoading,
  isGeneratingTable,
  onGenerateTable,
  onExportSql
}: {
  project?: Project;
  isLoading: boolean;
  isGeneratingTable: boolean;
  onGenerateTable: (tableId: string) => void;
  onExportSql: (tableId: string) => void | Promise<void>;
}) {
  const tables = project?.tables ?? [];
  const [selectedTableId, setSelectedTableId] = useState<string>();
  const selectedTable = useMemo(() => {
    if (tables.length === 0) return undefined;
    return tables.find((table) => table.id === selectedTableId) ?? tables[0];
  }, [selectedTableId, tables]);
  const latestSchema = selectedTable?.schemas?.[0];
  const references = project?.references ?? [];

  if (isLoading) {
    return <main className="min-w-0 p-5 text-sm text-slate-600">Loading project details...</main>;
  }

  if (!project) {
    return (
      <main className="grid min-w-0 place-items-center p-5">
        <div className="max-w-lg rounded-md border border-dashed border-line bg-white p-8 text-center">
          <h2 className="text-xl font-semibold">Generate a database model</h2>
          <p className="mt-2 text-sm text-slate-600">
            Select an existing project or click the plus button to describe a backend service and generate tables with Gemini.
          </p>
        </div>
      </main>
    );
  }

  return (
    <main className="min-w-0 p-5">
      <div className="mb-5 flex flex-wrap items-center justify-between gap-3">
        <div>
          <h2 className="text-2xl font-semibold">{selectedTable?.name ?? project.name}</h2>
          <p className="text-sm text-slate-600">{selectedTable?.description ?? project.description}</p>
        </div>
        <div className="flex gap-2">
          <button
            onClick={() => selectedTable && onGenerateTable(selectedTable.id)}
            disabled={!selectedTable || isGeneratingTable}
            className="inline-flex h-10 items-center gap-2 rounded-md bg-brand px-3 text-sm font-medium text-white hover:bg-teal-800 disabled:cursor-not-allowed disabled:opacity-70"
          >
            <Play className="h-4 w-4" aria-hidden="true" />
            {isGeneratingTable ? "Generating..." : "Generate"}
          </button>
          <button className="grid h-10 w-10 place-items-center rounded-md border border-line bg-white hover:bg-slate-50" title="Regenerate">
            <RotateCcw className="h-4 w-4" aria-hidden="true" />
          </button>
          <button
            onClick={() => selectedTable && onExportSql(selectedTable.id)}
            disabled={!latestSchema}
            className="grid h-10 w-10 place-items-center rounded-md border border-line bg-white hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-60"
            title="Export"
          >
            <Download className="h-4 w-4" aria-hidden="true" />
          </button>
        </div>
      </div>

      <div className="mb-4 flex flex-wrap gap-2">
        {tables.map((table) => (
          <button
            key={table.id}
            onClick={() => setSelectedTableId(table.id)}
            className={`rounded-md border px-3 py-2 text-sm font-medium ${table.id === selectedTable?.id ? "border-brand bg-teal-50 text-brand" : "border-line bg-white text-slate-700"}`}
          >
            {table.name}
          </button>
        ))}
      </div>

      <section className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(360px,0.75fr)]">
        <div className="rounded-md border border-line bg-white">
          <div className="border-b border-line px-4 py-3 font-semibold">Editable Schema Grid</div>
          <div className="overflow-x-auto">
            <table className="w-full min-w-[680px] text-left text-sm">
              <thead className="bg-slate-50 text-xs uppercase text-slate-600">
                <tr>
                  <th className="px-4 py-3">Column</th>
                  <th className="px-4 py-3">Type</th>
                  <th className="px-4 py-3">Nullable</th>
                  <th className="px-4 py-3">Notes</th>
                </tr>
              </thead>
              <tbody>
                {(latestSchema?.columnsJson ?? []).map((column) => (
                  <tr key={column.name} className="border-t border-line">
                    <td className="px-4 py-3 font-medium">{column.name}</td>
                    <td className="px-4 py-3">{column.type}</td>
                    <td className="px-4 py-3">{column.nullable === false ? "No" : "Yes"}</td>
                    <td className="px-4 py-3">{columnNote(column)}</td>
                  </tr>
                ))}
                {!latestSchema && (
                  <tr className="border-t border-line">
                    <td colSpan={4} className="px-4 py-8 text-center text-slate-500">
                      No schema has been generated for this table yet.
                    </td>
                  </tr>
                )}
              </tbody>
            </table>
          </div>
        </div>

        <div className="rounded-md border border-line bg-white">
          <div className="flex items-center gap-2 border-b border-line px-4 py-3 font-semibold">
            <GitPullRequestArrow className="h-4 w-4 text-accent" aria-hidden="true" />
            Suggested References
          </div>
          <div className="space-y-3 p-4">
            {references.map((reference) => (
              <div key={reference.id} className="rounded-md border border-line p-3">
                <div className="mb-3 text-sm font-medium">{referenceLabel(reference, tables)}</div>
                <div className="flex gap-2">
                  <span className="rounded-md bg-teal-50 px-3 py-2 text-xs font-medium text-brand">
                    {reference.accepted ? "Accepted" : "Suggested"}
                  </span>
                </div>
              </div>
            ))}
            {references.length === 0 && (
              <div className="rounded-md border border-dashed border-line p-4 text-sm text-slate-500">
                No references have been generated yet.
              </div>
            )}
          </div>
        </div>
      </section>
    </main>
  );
}
